### ISSUE TITLE
Why is subclassing JSONEncoder no longer recommended?

### ISSUE THREAD

**Issue by sprin** [simplejson/simplejson#124]
The docs for [`JSONEncoder.default`](https://simplejson.readthedocs.org/en/latest/#simplejson.JSONEncoder.default) say:
> Subclassing is not recommended. You should implement this as a function and pass it to the default kwarg of dumps(). This is faster and more portable than subclassing.

Why is using the `default` kwarg faster/more portable?

What is the recommended way of implementing the strategy pattern for custom JSON encoders if subclasses of `JSONEncoder` are not recommended?

Thanks for simplejson!

**Comment by etrepum** [comment]
Subclassing is very fragile, it's easy to override something unintentionally or have a namespace conflict between your attributes and the attributes of the parent class. Since the parent class can add or remove attributes over time, this is just unmaintainable and not easy to port between versions.

The best way to implement this feature is with composition, where the "type encoding strategy" is an argument to the encoder. Since there is only one thing to override, the strategy is simply a callable rather than a class with some methods.

Switching to a default method is faster because simplejson can do caching of instances when certain arguments are not overridden.

**Comment by sprin** [comment]
Thanks for the explanation! It sounds like frameworks that want to support custom JSON encoders should switch to allowing a "default" callable to be supplied, rather than a `JSONEncoder` subclass.
