### ISSUE TITLE
encoding of `\u2028` and `\u2029` inconsistent with `json` with ensure_ascii=False

### ISSUE THREAD

**Issue by richvdh** [simplejson/simplejson#206]
If you set `ensure_ascii=False`, the standard `json` module leaves `\u2028` and `\u2029` (line separator and paragraph separator) as their unicode characters; simplejson encodes them as `\u` escapes:

```
>>> json.dumps([u"\u2028"], ensure_ascii=False).encode('utf-8')
b'["\xe2\x80\xa8"]'
>>> simplejson.dumps([u"\u2028"], ensure_ascii=False).encode('utf-8')
b'["\\u2028"]'
```

(Tested on python 2.7.12 and 3.5.2, against simplejson 3.12.3)

Of course the `\u` escape is a valid encoding of these characters, but for various reasons I'm after the unencoded version. At the very least, the inconsistency with stock json is surprising.

**Comment by etrepum** [comment]
It's certainly not intentional, a PR to make this behavior consistent would be appreciated. The divergence here most likely happened on the Python side and the change just didn't get communicated back to here.

**Comment by serhiy-storchaka** [comment]
I think this is intentional. This helps embedding JSON in JavaScript. JSON is not JavaScript, JavaScript doesn't allow line separator and paragraph separator in string literals. Making simplejson not escaping these characters can break existing code.

The standard json module doesn't escape these characters because the standard doesn't require this, and adding them to the set of characters that need to be escaped would make serialization a tiny bit slower. In any case you would need to escape also the closing tag `</SCRIPT>` if it occurred in the string.

Therefore json doesn't escape these characters because doing this has a non-zero cost, and simplejson escapes them for historical reasons, and can't stop because this will break existing code.

**Comment by etrepum** [comment]
Looks like escaping this particular character was introduced in v2.2.0 https://github.com/simplejson/simplejson/blob/master/CHANGES.txt#L397-L398

Before changing this behavior, it'd be good to check recent and draft RFCs and other standards to see what their current position is on the encoding of this character.

**Comment by richvdh** [comment]
[RFC 8259](https://tools.ietf.org/html/rfc8259) says:

```
unescaped = %x20-21 / %x23-5B / %x5D-10FFFF
```

[ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) says:

> All code points may be placed within the quotation marks except for the code points that must be escaped: quotation mark (U+0022), reverse solidus (U+005C), and the control characters U+0000 to U+001F

Both standards therefore allow U+2028 and U+2029 to be left unescaped in JSON.

The change in simplejson 2.2.0 appears to have been made to ensure that we produce JSON that is valid Javascript (ie, can be used in JSONP), which is a reasonable goal, but I find it regrettable it was done without putting it behind an option flag, because as @serhiy-storchaka says, reversing the change does risk breaking existing code.

On the other hand, I still feel like the inconsistency with `json` is the bigger risk here.

Anyway, a reasonable compromise might be to put this behaviour behind an option flag along the lines of `ensure_ascii`, with it defaulting to the current behaviour?

**Comment by etrepum** [comment]
I would rather just increment the version number appropriately and change the ensure_ascii=False behavior to match current specifications and the json module.

**Comment by etrepum** [comment]
To preserve compatibility with the HTML/JS embedding use case we should make sure that this escaping occurs in the `JSONEncoderForHTML` encoder regardless of the ensure_ascii setting.
