### ISSUE TITLE
Documentation CSS

### ISSUE THREAD

**Issue by yoooooooooooooooooooooooo** [simplejson/simplejson#221]
When I use `./scripts/make_docs.py` the HTML is not well formatted. It looks like it's missing some CSS styles. How can I fix it?

**Comment by etrepum** [comment]
I haven't kept up maintenance of that toolchain since we started using readthedocs, where it formats nicely: http://simplejson.readthedocs.io/en/latest/

It's likely that something in sphinx, pygments, or docutils changed over the years that would require some changes on our end to make it look good again.

**Comment by etrepum** [comment]
Looks like the change to fix this is pretty small, give this a shot and let me know if it works for you: https://github.com/simplejson/simplejson/pull/222/files
