### ISSUE TITLE
Question: Comparison with other Python-JSON packages

### ISSUE THREAD

**Issue by MartinThoma** [simplejson/simplejson#267]
I'm currently comparing various Python packages for handling JSON ([link](https://github.com/MartinThoma/algorithms/tree/master/Python/json-benchmark): cpython 3.8.6 json, simplejson, ujson, simdjson, orjson, rapidjson). I'm trying to understand their differences. I would be super happy if you could help me with that by answering some questions:

1. Is there any difference in features between the JSON packages?
2. I compared reading/dumping a 2.3MB GeoJSON and a 631KB Twitter JSON. Is there any other thing you think I should compare for benchmarking? Do you have internal benchmarks?
3. I've seen that there is "an optional C extension for a serious speed boost" - how do I make sure I use it?
4. Are you in contact with the other Python JSON package developers? Do you maybe share the way you benchmark or test cases?
5. Are you in contact with JSON package developers from other languages?
6. Are there other packages / articles for comparison I should have a look at?

**Comment by MartinThoma** [comment]
I see that `simplejson` was included into cpython as `json` in Python 2.4 ([source](https://docs.python.org/3/whatsnew/2.6.html#the-json-module-javascript-object-notation)). Are the two now developed separately or are they still synced (once in a while)?

**Comment by etrepum** [comment]
1. I don't actively research other JSON libraries.
2. You should be benchmarking results that are close to your use case, whatever that may be. I had internal ones years ago when I was actively using and developing this project, but I don't think they ever got open sourced anywhere.
3. In almost all cases it should be used, you can make the build fail if speedups are not enabled by setting the `REQUIRE_SPEEDUPS` environment variable, e.g. `env REQUIRE_SPEEDUPS=1 python3 setup.py build`
4. I'm only in sporadic contact with the cpython team
5. I was ~15 years ago when the project started, but the JSON spec and simplejson API hasn't changed all that much since. This project is in maintenance mode.
6. You're better off asking these questions of the newer libraries.

simplejson and cpython's json have not been synced on a regular basis in many years. The source code for Python does not maintain backwards compatibility for Python 2, so it's a large effort to move code in either direction way.

**Comment by MartinThoma** [comment]
Thank you for taking the time to answer 🤗

**Comment by serhiy-storchaka** [comment]
`simplejson` is compatible with standard `json` module, but supports old Python versions and have few additional features. It is mostly used if you need to support old Python 2 versions or already use some `simplejson` features.

Most libraries provide interface compatible with `simplejson` and standard `json` module. Some support also a stream mode and/or has builting filter and query sub-language.

Other libraries may be more performant for reading or writing large lists of floats, but at the cost of losing precision. JSON may be not optimal format for such data.

Also, one of libraries that I tested several years ago (don't remember the name) was very unstable and could crash.
