### ISSUE TITLE
3.19.1 contained a breaking change by changing `allow_nan` to default to false

### ISSUE THREAD

**Issue by mistercrunch** [simplejson/simplejson#324]
Hey friendly note to say that changing `allow_nan` to default to `False` in `3.19.1` was a breaking change. Ideally according to semver it should have triggered a `4.x` release, or held back until 4.x would have been ready. I'd love if this library could subscribe to the semver principles moving forward!

Thanks for a great library!

**Comment by etrepum** [comment]
Thanks for the note! Since this library is nearly 20 years old, it predates semver. Generally speaking the library has a very solid backwards compatibility record, although that change in particular was also done for security reasons. At this point very few other implementations also support this feature and I believe that none have it as a default, so it was not held back.

**Comment by mistercrunch** [comment]
No big deal, but somehow broke a unit test on my side -> https://github.com/apache/superset/blob/master/tests/integration_tests/utils/hashing_tests.py#L89

Not sure what the implications of switching to semver would mean here, but something to consider. On our side we typically only review changelogs when bumping across major versions.

**Comment by mistercrunch** [comment]
Oh curious what the implications of `allow_nan = True` are (?)

**Comment by etrepum** [comment]
In this case it's because `'{"company": "Gobias Industries", "price": NaN, "product": "Coffee"}'` is not valid JSON, although it is accepted and produced by previous versions of simplejson. This was a historical mistake from before there was a proper spec for JSON. This change fixed that mistake so that by default simplejson will only produce and consume valid JSON.

**Comment by etrepum** [comment]
The full report is here https://www.x41-dsec.de/static/reports/X41-OSTIF-simplejson-CodeRview-2023-04-18.pdf

**Comment by mistercrunch** [comment]
Yes, and it's unclear how much our other usage of simplejson in supserset may depend on that "feature". For instance it seems numpy has similar `np.NaN` semantics and there's some serialization/deserialization that take place between numpy/simplejosn. We may want to take a similar stance as the one you took here around "it was wrong anyways" and accept that bumping this library could break things that shouldn't have worked in the first place...

**Comment by etrepum** [comment]
Yeah, I'm willing to live with that. This breaking change came out about a year ago and you are the only person who has brought it up here.
